services:
  - type: web
    name: todo-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma migrate deploy && npx prisma generate
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        value: file:./dev.db
